# Generated by scripts/render-packaging.sh. Do not edit by hand; edit the template.
class Svipall < Formula
  desc "Local-first web scraping and captcha MCP server for AI agents"
  homepage "https://github.com/ilien-dev/svipall"
  version "1.3.1"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/ilien-dev/svipall/releases/download/v1.3.1/svipall-1.3.1-aarch64-apple-darwin.tar.gz"
      sha256 "6083c16ec757fce25512e133667afffbf128bf721f7a2fc026504b2d608465be"
    end
    # No `on_intel`: Intel macOS has no build, and a formula that names a URL the release does not
    # publish fails at download time with nothing useful to read. `brew install` declines here
    # instead, and docs/install.md names the container image.
  end

  on_linux do
    on_arm do
      url "https://github.com/ilien-dev/svipall/releases/download/v1.3.1/svipall-1.3.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "4b7e145973ae5904c58bf382a9a125ae43292fa3488596c56e46fe931a79710b"
    end
    on_intel do
      url "https://github.com/ilien-dev/svipall/releases/download/v1.3.1/svipall-1.3.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "8d6f49e4cc3a02cffecf46f65f4c92cfa2e767c2a134843442eda1fcfa528305"
    end
  end

  def install
    bin.install "svipall"
    bin.install "svipall-mcp"
    doc.install "README.md"
    # The agent skill, next to the binaries it documents, where an agent can be pointed at it.
    pkgshare.install "SKILL.md"
  end

  def caveats
    <<~EOS
      Browser tiers need a Chromium-based browser. Either install Chrome or Edge, or let
      svipall keep one of its own (~190 MB):

        svipall browser install

      Then check what this installation can do:

        svipall doctor

      To use it from Claude Code:

        claude mcp add svipall -- svipall-mcp
    EOS
  end

  test do
    assert_match "\"version\": \"#{version}\"", shell_output("#{bin}/svipall --version")
    assert_match "\"problems\"", shell_output("#{bin}/svipall doctor")
  end
end
