# Generated by scripts/render-packaging.sh. Do not edit by hand; edit the template.
class Svipall < Formula
  desc "Local-first web scraping and captcha MCP server for AI agents"
  homepage "https://github.com/ilien-dev/svipall"
  version "1.2.0"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/ilien-dev/svipall/releases/download/v1.2.0/svipall-1.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "5e4300650bb81f6436dc5633ff229b9db1e5b6db6dd63d150e1a273c98b7abf7"
    end
    # No `on_intel`: Intel macOS has no build, and a formula that names a URL the release does not
    # publish fails at download time with nothing useful to read. `brew install` declines here
    # instead, and docs/install.md names the container image.
  end

  on_linux do
    on_arm do
      url "https://github.com/ilien-dev/svipall/releases/download/v1.2.0/svipall-1.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "34fc78050a9d5ee6d7fa455a6fa54f861e93cc34b58f492c92c9c6b972fa8b76"
    end
    on_intel do
      url "https://github.com/ilien-dev/svipall/releases/download/v1.2.0/svipall-1.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c2d11a8915167f1a592865bfc89bff5a723bae893afb45e4f40f65ff8fc78aa2"
    end
  end

  def install
    bin.install "svipall"
    bin.install "svipall-mcp"
    doc.install "README.md"
    # The agent skill, next to the binaries it documents, where an agent can be pointed at it.
    pkgshare.install "SKILL.md"
  end

  def caveats
    <<~EOS
      Browser tiers need a Chromium-based browser. Either install Chrome or Edge, or let
      svipall keep one of its own (~190 MB):

        svipall browser install

      Then check what this installation can do:

        svipall doctor

      To use it from Claude Code:

        claude mcp add svipall -- svipall-mcp
    EOS
  end

  test do
    assert_match "\"version\": \"#{version}\"", shell_output("#{bin}/svipall --version")
    assert_match "\"problems\"", shell_output("#{bin}/svipall doctor")
  end
end
