# Generated by scripts/render-packaging.sh. Do not edit by hand; edit the template.
class Svipall < Formula
  desc "Local-first web scraping and captcha MCP server for AI agents"
  homepage "https://github.com/ilien-dev/svipall"
  version "1.0.6"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/ilien-dev/svipall/releases/download/v1.0.6/svipall-1.0.6-aarch64-apple-darwin.tar.gz"
      sha256 "b284f49e6453b2c45b15758d6d1241a3cb70376527d6c78470979ff7e12b2459"
    end
    # No `on_intel`: Intel macOS has no build, and a formula that names a URL the release does not
    # publish fails at download time with nothing useful to read. `brew install` declines here
    # instead, and docs/install.md names the container image.
  end

  on_linux do
    on_arm do
      url "https://github.com/ilien-dev/svipall/releases/download/v1.0.6/svipall-1.0.6-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0c3956fd6a1aca4d53d09ea0555a85c490cd6447ab62a3c22120bc6d9c53a2c7"
    end
    on_intel do
      url "https://github.com/ilien-dev/svipall/releases/download/v1.0.6/svipall-1.0.6-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c3339d898177c6afe58b07ddbaa698a5d5a28daf5d5bdbb1f831db9d776b4b6d"
    end
  end

  def install
    bin.install "svipall"
    bin.install "svipall-mcp"
    doc.install "README.md"
    # The agent skill, next to the binaries it documents, where an agent can be pointed at it.
    pkgshare.install "SKILL.md"
  end

  def caveats
    <<~EOS
      Browser tiers need a Chromium-based browser. Either install Chrome or Edge, or let
      svipall keep one of its own (~190 MB):

        svipall browser install

      Then check what this installation can do:

        svipall doctor

      To use it from Claude Code:

        claude mcp add svipall -- svipall-mcp
    EOS
  end

  test do
    assert_match "\"version\": \"#{version}\"", shell_output("#{bin}/svipall --version")
    assert_match "\"problems\"", shell_output("#{bin}/svipall doctor")
  end
end
